name: Run Visual Testing on PR comment

on:
  issue_comment:
    types:
      - created

env:
  NODE_VERSION: 20.x

jobs:
  run-visial-testing:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run visual now' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get the pull request information
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issueNumber,
            });

            core.setOutput('branch_name', pullRequest.head.ref);
            core.setOutput('commit_sha', pullRequest.head.sha);

      - uses: bahmutov/npm-install@v1

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - run: npm run test:visual
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
