name: Run Visual Testing on PR comment

on:
  issue_comment:
    types:
      - created

env:
  NODE_VERSION: 20.x

jobs:
  run-visual-testing:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run visual now' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get the pull request information
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issueNumber,
            });

            core.setOutput('base_branch', pullRequest.base.ref); // Get the base branch
            core.setOutput('base_commit', pullRequest.base.sha); // Get the base commit

      - uses: bahmutov/npm-install@v1

      - name: Check pull request values
        run: |
          echo "Base branch: ${{ steps.get_pr.outputs.base_branch }}"
          echo "Base commit: ${{ steps.get_pr.outputs.base_commit }}"

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - run: npm run test:playwright
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          REFERENCE_BRANCH: ${{ steps.get_pr.outputs.base_branch }}
          REFERENCE_COMMIT: ${{ steps.get_pr.outputs.base_commit }}